# general alias
alias ls='ls --color=auto'
alias l='ls -F'
alias ll='ls -l'
alias la='ls -A'
alias cd..='cd ..'
alias grep='grep --color=auto'
alias biggest='find -type f -printf '\''%s %p\n'\'' | sort -nr | head -n 40 | gawk "{ print \$1/1000000 \" \" \$2 \" \" \$3 \" \" \$4 \" \" \$5 \" \" \$6 \" \" \$7 \" \" \$8 \" \" \$9 }"'
alias upgrade='sudo apt-get update && sudo apt-get upgrade'

# git alias
alias gad='git add'
alias gcm='git commit'
alias gs='git status'
alias glg='git log --format="%C(yellow)%h %Cblue%ad %Cgreen%aN %Cred%d %Creset%s" --graph --decorate --color --all --date=short'
alias glgbr='git log --format="%C(yellow)%h %Cblue%ad %Cgreen%aN %Cred%d %Creset%s" --graph --decorate --color --date=short'
alias gps='git push'
alias gpl='git pull --prune'
alias gfc='git fetch --prune'
alias gbr='git branch'
alias gch='git checkout'
alias gst='git stash'
alias grs='git reset'
alias gcl='git clean -fd'
alias grm='git remote'
alias gm='git merge'
alias gft='git fetch'
alias gdf='git diff --color'
alias glist='git show --pretty="" --name-only'
alias gcp='git cherry-pick'
